# Generated by Django 4.0.1 on 2022-02-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('media', models.CharField(max_length=150)),
                ('gallery', models.CharField(max_length=150)),
                ('banner_image', models.CharField(max_length=150)),
                ('goal', models.CharField(max_length=150)),
                ('amount_collected', models.CharField(max_length=150)),
                ('contact_details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=150)),
                ('sender_name', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('class_of', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=10)),
                ('have_paid_dues', models.BooleanField(default=False)),
                ('current_work', models.CharField(blank=True, max_length=150, null=True)),
                ('has_contributions', models.BooleanField(default=False)),
                ('achievements', models.TextField(blank=True, max_length=2500, null=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2500)),
                ('media', models.CharField(max_length=150)),
                ('coaches', models.ManyToManyField(related_name='coaches', to='main.Member')),
                ('members_of_team', models.ManyToManyField(related_name='members_of_team', to='main.Member')),
                ('type_of_team', models.ManyToManyField(to='main.CategoryOfTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2500)),
                ('image', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('team_organization', models.ManyToManyField(to='main.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=150)),
                ('member_ID', models.ManyToManyField(to='main.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('banner_image', models.CharField(max_length=150)),
                ('gallery', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2500)),
                ('media', models.CharField(max_length=150)),
                ('registration_fees', models.CharField(max_length=150)),
                ('rsvpd_members', models.ManyToManyField(to='main.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaigns', models.ManyToManyField(to='main.Campaign')),
                ('events', models.ManyToManyField(to='main.Event')),
                ('members', models.ManyToManyField(to='main.Member')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='members_who_donated',
            field=models.ManyToManyField(to='main.Member'),
        ),
    ]
