# Generated by Django 3.2 on 2022-03-15 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=150)),
                ('media', models.ImageField(blank=True, upload_to='media/Campaign Media')),
                ('gallery', models.FileField(blank=True, upload_to='media/Campaign Media')),
                ('banner_image', models.ImageField(blank=True, upload_to='media/Campaign Media')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_collected', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10)),
                ('contact_details', models.CharField(max_length=150)),
                ('members_who_donated', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('year', models.IntegerField(default=2000)),
                ('description', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=150)),
                ('sender_name', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=40)),
                ('time', models.CharField(blank=True, max_length=40, null=True)),
                ('address_line', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(default='LA', max_length=50)),
                ('zip_code', models.CharField(max_length=150)),
                ('contact_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, default=None, max_length=150, null=True)),
                ('banner_image', models.ImageField(default='EventBannerDefault.jpg', upload_to='')),
                ('description', models.TextField(max_length=2500)),
                ('registration_fees', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2500)),
                ('media', models.ImageField(blank=True, upload_to='media/Team Media')),
                ('coaches', models.ManyToManyField(blank=True, related_name='coaches', to=settings.AUTH_USER_MODEL)),
                ('members_of_team', models.ManyToManyField(related_name='members_of_team', to=settings.AUTH_USER_MODEL)),
                ('type_of_team', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.categoryofteam')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=2500)),
                ('image', models.ImageField(blank=True, upload_to='media/Scholarship Media')),
                ('amount', models.CharField(max_length=150)),
                ('team_organization', models.ManyToManyField(blank=True, to='main.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, max_length=150)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(default='Friend', max_length=400)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.userprofile')),
                ('user2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='media/Event Media')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaigns', models.ManyToManyField(to='main.Campaign')),
                ('events', models.ManyToManyField(to='main.Event')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
