# Generated by Django 3.2 on 2022-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_gallery',
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
