# Generated by Django 3.2 on 2022-03-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='team',
            name='media',
        ),
        migrations.RemoveField(
            model_name='team',
            name='type_of_team',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='media/Event Media'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='home_gallery_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/Home Gallery'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sub_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_of_team',
            field=models.ManyToManyField(blank=True, related_name='members_of_team', to=settings.AUTH_USER_MODEL),
        ),
        
    ]
