# Generated by Django 3.2 on 2022-03-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220314_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
