# Generated by Django 4.0.1 on 2022-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_member_address_member_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rsvpd_members',
            field=models.ManyToManyField(blank=True, null=True, to='main.Member'),
        ),
    ]
