# Generated by Django 3.2 on 2022-03-12 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20220307_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='media',
        ),
        migrations.RemoveField(
            model_name='team',
            name='type_of_team',
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='sub_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(blank=True, null=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_of_team',
            field=models.ManyToManyField(blank=True, null=True, related_name='members_of_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CategoryOfTeam',
        ),
    ]
