# Generated by Django 4.0.1 on 2022-02-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_rsvpd_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.ImageField(upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='members_who_donated',
            field=models.ManyToManyField(blank=True, null=True, to='main.Member'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvpd_members',
            field=models.ManyToManyField(to='main.Member'),
        ),
    ]
