# Generated by Django 3.2 on 2022-03-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userprofile',
        ),
    ]
