# Generated by Django 3.2 on 2022-03-15 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220314_2105'),
        ('main', '0004_auto_20220314_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.userprofile'),
        ),
    ]
