# Generated by Django 3.2 on 2022-03-12 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20220311_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_of_team',
            field=models.ManyToManyField(blank=True, related_name='members_of_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
