# Generated by Django 3.2 on 2022-03-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220314_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='user2',
        ),
    ]
