# Generated by Django 3.2 on 2022-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220311_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='home_gallery_images',
            field=models.FileField(default='', upload_to='media/Home Gallery'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
