# Generated by Django 4.0.1 on 2022-02-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_campaign_amount_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
    ]
