# Generated by Django 3.2 on 2022-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220312_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='home_gallery_images',
            new_name='home_gallery_image',
        ),
    ]
