# Generated by Django 3.2 on 2022-02-09 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='member_ID',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year',
        ),
        migrations.AddField(
            model_name='categoryofteam',
            name='year',
            field=models.IntegerField(default=1999, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='members_who_donated',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvpd_members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_of_team',
            field=models.ManyToManyField(related_name='members_of_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
