# Generated by Django 3.2 on 2022-02-09 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220208_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='type_of_team',
        ),
        migrations.AddField(
            model_name='team',
            name='type_of_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categoryofteam'),
            preserve_default=False,
        ),
    ]
