# Generated by Django 3.2 on 2022-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_home_gallery_images_gallery_home_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='event_images',
        ),
    ]
