# Generated by Django 3.2 on 2022-03-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_images_gallery_event_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='event_images',
            new_name='event_image',
        ),
    ]
