# Generated by Django 3.2 on 2022-02-09 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20220208_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='members',
        ),
        migrations.AddField(
            model_name='contribution',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
