# Generated by Django 3.2 on 2022-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='EventBannerDefault.jpg', null=True, upload_to='media'),
        ),
    ]
