# Generated by Django 3.2 on 2022-02-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220208_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='members',
            new_name='user',
        ),
    ]
