# Generated by Django 3.2 on 2022-03-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220312_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event_image',
            field=models.FileField(blank=True, null=True, upload_to='media/Event Media'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='home_gallery_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='media/Home Gallery'),
        ),
    ]
