# Generated by Django 3.2 on 2022-03-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_verified'),
        ('main', '0011_auto_20220312_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.userprofile'),
        ),
    ]
