# Generated by Django 3.2 on 2022-03-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_verified'),
        ('main', '0012_auto_20220315_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='accounts.userprofile'),
        ),
    ]
